import type { Metadata } from "next";
import "./globals.css";
import { Manrope } from "next/font/google";
import { Toaster } from "@/components/ui/sonner";
import AuthProvider from "@/components/providers/AuthProvider";
import AppProvider from "@/components/providers/AppProvider";
import NextTopLoader from 'nextjs-toploader'

const manrope = Manrope({
  subsets: ["latin"],
  weight: ["200","300","400","500","600","700","800"],
  variable: "--font-manrope",
});

export const metadata: Metadata = {
  title: "Mireyags Website",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" >
      <body className={`${manrope.variable} font-manrope antialiased`}>
        <NextTopLoader color="#00B6E0" height={3} showSpinner={false}  />
        <AuthProvider>
          <AppProvider>

            {children}

            <Toaster />
          </AppProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
